name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to v3

    - name: Set up Node.js
      uses: actions/setup-node@v3  # Updated to v3
      with:
        node-version: '20'  # Updated to Node.js 20

    - name: Install dependencies
      run: npm install

    - name: Print environment variables
      run: |
        echo "API_URL=${{ secrets.API_URL }}"
        echo "API_TOKEN=${{ secrets.API_TOKEN }}"

    - name: Fetch and build
      run: npm run build
      env:
        API_URL: ${{ secrets.API_URL }}
        API_TOKEN: ${{ secrets.API_TOKEN }}

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4  # Updated to v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
